### ISSUE TITLE
How would I use this plugin?

### ISSUE THREAD

**Issue by MichaelAGordon** [andmcadams/plugin-repo#1]
I go up to the telescope check the star and I get no indications that anything has happened, how do you actually use this plugin?

**Comment by andmcadams** [comment]
You either need to set up your own server to accept requests (see https://github.com/andmcadams/shooting-stars-node) or wait for the PR for version 1.1 to be merged by the plugin hub. Version 1.1 has a default set of endpoints that will store your scout information.

**Comment by andmcadams** [comment]
This is fixed with the version 1.2 release. It now comes with default API endpoints and sharedKey so it works without having to configure anything.
