### ISSUE TITLE
[Change request]

### ISSUE THREAD

**Issue by Thereatra** [andmcadams/plugin-repo#16]
In commit 3e4166d4802857097cede9ed09fc9c0563fdeaa2 you removed f2p worlds from the list, please consider adding them back as shootings stars is in fact [not a member only activity](https://oldschool.runescape.wiki/w/Shooting_Stars), and it is very useful for f2p ironmen in order to get soft clay.

**Comment by breakthetargets** [comment]
The fact that f2p worlds can't be scoped in the first place (how will there be data for F2P in the first place if you used the plugin in the way it's intended?) is why I think removing it was a good change.

**Comment by andmcadams** [comment]
Yeah, I removed it since you can't actually scout them via the telescope. In theory, I guess someone using their own server could scout them after landing and push some data up manually if they have a different server setup. Does anyone currently do this @Thereatra ? If so, I'll gladly revert the change.

I did it in order to reduce garbage being read from the server in case people send spam to the server, though this change could be done server side so it doesn't impact other people's use cases.

**Comment by Thereatra** [comment]
To be completely honest I hadn't thought about the scouting with telescope part and just silently assumed that stars were also pushed to the server if they were found in location, if they weren't already known. My bad, guess I should have read the readme. Some form of f2p support would be really nice, but I now understand that it not possible the way the plugin is right now.

I guess at this point this turns into a feature request instead then. Would you consider adding the possibility to automatically send information about stars that has already landed and not seen yet? Or maybe a way to shift + right-click and manually send information.

**Comment by andmcadams** [comment]
I would not want to allow a way to manually send info. That would make it significantly easier for people to send in fake data or troll others and significantly increase the complexity of the plugin.

> Would you consider adding the possibility to automatically send information about stars that has already landed and not seen yet?

I'm not sure I understand here. Is this meant to help f2p? Or do you just mean reporting when you look through a telescope and don't see a star (implying it has fallen)? Maybe I'm misunderstanding, but I'm not sure this would work. When you can't see a star through the telescope, it does not necessarily mean one is still on the ground now.

**Comment by Thereatra** [comment]
Yeah sorry it probably wasn't phrased that well, so here is an example. You walk around the world and see a crashed star on the ground, a message is then automatically sent to your server to tell where the star is.

The left click option I meant was simply that instead of sending this information automatically to the server when walking past a star, a player would have to shift + right-click the star in game in order to send the same message.

The way this would be useful for f2p players is that it adds an option to share crashed stars to your server without having to use a telescope, which is a thing you can't do. In short it would allow some form of sharing crashed stars on f2p worlds.

**Comment by andmcadams** [comment]
This is very similar to a rejected feature, "Recording the exact location and tier of a star when you see it land". While it is a little different in that you have to manually share it, this still greatly increases the complexity of the plugin for a relatively niche feature. I wouldn't want to add that to this plugin.
