### ISSUE TITLE
[feature request] Make the side panel button hideable / toggleable / etc

### ISSUE THREAD

**Issue by etc597** [andmcadams/plugin-repo#19]
Ability to hide the side panel button in runelite. I want to provide data but don't particularly care about hunting stars myself and would like to declutter my side panel. Hablapatabla's [Impling Finder](https://github.com/Hablapatabla/ImplingFinder) already does this for reference on how to implement it. Would be very nice to have.

**Comment by andmcadams** [comment]
See [this diff](https://github.com/andmcadams/plugin-repo/compare/f80fc879aa36beef86963491eea22a2a2a59048f..fd6a2397c80ca9b686b37a8a6620d1a3a90b595b), will test when I have a chance. There's a bit of logic involved when switching panel types so I want to make sure you don't end up with two icons in some cases.

**Comment by andmcadams** [comment]
This was added a few days ago, forgot to mention this issue. Should be live now that the plugin hub PR has been merged. Version 1.6.2, you might need to restart your client if you are still running the old version. Thanks for the suggestion!
