### ISSUE TITLE
[Feature Request] F2P world only or P2P worlds only

### ISSUE THREAD

**Issue by SirJorb** [andmcadams/plugin-repo#20]
It would be nice if you could filter by F2P or P2P world, if possible. On a F2P account it's a bit annoying seeing all the P2P stars and having to check all of them to see if they're in an accessible world. It would be nice if I could just click a button and only see F2P world stars, so I know that if I see any, I can go there.

Likewise, I'm sure there are P2P players who'd rather not see any F2P world meteors since it'll disable their members items while there.

**Comment by andmcadams** [comment]
There shouldn't be a way to scout f2p worlds with this plugin since telescopes (and POHs) are not f2p. Is there some way to scout them that I'm missing?

**Comment by SirJorb** [comment]
Oh, I might be a little bit stupid. I guess I assumed there were manual calls integrated in too but now that I think about it I’m not sure how that’d work. No wonder I never saw any F2P listed, whoops.
